development:
  adapter: postgresql
  encoding: unicode
  database: jacky_game_chest_development
  pool: 5
  username: jackygamechest
  password: jackygamechest
  host: localhost
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: jacky_game_chest_test
  pool: 5
  username: jackygamechest
  password: jackygamechest
  host: localhost
  timeout: 5000
